---
title: "Ovsanna"
author: "Tao Guo"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Environment

```{r, echo=FALSE, warning=FALSE, include=FALSE}
library(ggplot2)
library(readxl)
library(lmerTest)
library(stats)
library(ordinal)
library(nlme)
library(dplyr)

data<- read_excel("Daily Monitor Tracking Log.xlsx")
```
```{r, warning=FALSE}

#Choose problem
newdata <- data[which(data$...3=="Average Anxiety Today"),]
newdata <- newdata[,-c(1:3)]
p <- as.matrix(newdata)
y <- c(t(p))
y <- y[!is.na(y)] 
t <- c(1:22,1:29,1:22,1:36,1:29,1:29,1:35,1:29)
T <- c(rep(0,14),rep(1,8),rep(0,21),rep(1,8),rep(0,14),rep(1,8),rep(0,28),rep(1,8),rep(0,21),rep(1,8),rep(0,21),rep(1,8),rep(0,28),rep(1,7),rep(0,21),rep(1,8))
ID <- c(rep(1,22),rep(5,29),rep(3,22),rep(6,36),rep(9,29),rep(12,29),rep(11,35),rep(17,29))
m <- data.frame(y,ID,t,T)
m$y <- as.numeric(y)
```
```{r}
model2 <- lmer(y ~ T + t*T + (1 | as.factor(ID)), data = m)
m$y_pred <- fitted(model2)
summary(model2)
```
```{r}
vline_data <- data.frame(ID = c(1,3,5,6,9,11,12,17),  xintercept=c(15,15,22,29,22,29,22,22) )
```

```{r}
ggplot(m, mapping = aes(x=t, y=y_pred, group=as.factor(ID))) +
  geom_line()+geom_line(aes(x=t, y=y, group=as.factor(ID), colour=as.factor(ID))) +facet_wrap(~ID)+ggtitle("Average Anxiety Today")+geom_vline(data = vline_data, aes(xintercept = xintercept, group = as.factor(ID)), linetype = "dashed")
```

```{r}
 m$resid <- resid(model2)
acf(m[m$ID==1,]$resid)
```
```{r}
fm1 <- lme(y ~ T+t*T, random = ~1|as.factor(ID),correlation = corAR1(),data = m)
summary(fm1)
```


```{r}
m$resid <- resid(fm1)
acf(m[m$ID==1,]$resid)
```




```{r}
m$y <- as.factor(m$y)
model <- clmm(ordered(y) ~ T + t*T + (1 | as.factor(ID)), data = m)
summary(model)

```
##Max Anxiety Today
```{r}
newdata <- data[which(data$...3=="Max Anxiety Today"),]
newdata <- newdata[,-c(1:3)]
p <- as.matrix(newdata)
y <- c(t(p))
y <- y[!is.na(y)] 
t <- c(1:22,1:29,1:22,1:36,1:29,1:29,1:35,1:29)
T <- c(rep(0,14),rep(1,8),rep(0,21),rep(1,8),rep(0,14),rep(1,8),rep(0,28),rep(1,8),rep(0,21),rep(1,8),rep(0,21),rep(1,8),rep(0,28),rep(1,7),rep(0,21),rep(1,8))
ID <- c(rep(1,22),rep(5,29),rep(3,22),rep(6,36),rep(9,29),rep(12,29),rep(11,35),rep(17,29))
m1 <- data.frame(y,ID,t,T)
m1$y <- as.numeric(y)
```

```{r}
model3 <- lmer(y ~ T + t*T + (1 | as.factor(ID)), data = m1)
m1$y_pred <- fitted(model3)
summary(model3)
```
```{r}
ggplot(m1, mapping = aes(x=t, y=y_pred, group=as.factor(ID))) +
  geom_line()+geom_line(aes(x=t, y=y, group=as.factor(ID), colour=as.factor(ID))) +facet_wrap(~ID)+ggtitle("Max Anxiety Today")+geom_vline(data = vline_data, aes(xintercept = xintercept, group = as.factor(ID)), linetype = "dashed")
```
```{r}
m1$resid <- resid(model3)
acf(m1[m1$ID==1,]$resid)
```
```{r}
fm2 <- lme(y ~ T+t*T, random = ~1|as.factor(ID),correlation = corAR1(),data = m1)
summary(fm2)
```
```{r}
m1$resid <- resid(fm2) 
acf(m1[m1$ID==1,]$resid)
```
```{r}
m1$y <- as.factor(m1$y)
ordnal1 <- clmm(ordered(y) ~ T+t*T + (1 | as.factor(ID)), data = m1)
summary(ordnal1)
```
##Avg Avoidance of Thoughts, Situatoins, Sensations
```{r}
newdata <- data[which(data$...3=="Avg Avoidance of Thoughts, Situatoins, Sensations"),]
newdata <- newdata[,-c(1:3)]
p <- as.matrix(newdata)
y <- c(t(p))
y <- y[!is.na(y)] 
t <- c(1:22,1:29,1:22,1:36,1:29,1:29,1:35,1:29)
T <- c(rep(0,14),rep(1,8),rep(0,21),rep(1,8),rep(0,14),rep(1,8),rep(0,28),rep(1,8),rep(0,21),rep(1,8),rep(0,21),rep(1,8),rep(0,28),rep(1,7),rep(0,21),rep(1,8))
ID <- c(rep(1,22),rep(5,29),rep(3,22),rep(6,36),rep(9,29),rep(12,29),rep(11,35),rep(17,29))
m2 <- data.frame(y,ID,t,T)
m2$y <- as.numeric(y)
```

```{r}
model4 <- lmer(y ~ T + t*T + (1 | as.factor(ID)), data = m2)
m2$y_pred <- fitted(model4)
summary(model4)
```
```{r}
ggplot(m2, mapping = aes(x=t, y=y_pred, group=as.factor(ID))) +
  geom_line()+geom_line(aes(x=t, y=y, group=as.factor(ID), colour=as.factor(ID))) +facet_wrap(~ID)+ggtitle("Avg Avoidance of Thoughts, Situatoins, Sensations")+geom_vline(data = vline_data, aes(xintercept = xintercept, group = as.factor(ID)), linetype = "dashed")
```
```{r}
m2$resid <- resid(model4)
acf(m2[m2$ID==11,]$resid)
```
```{r}
fm3 <- lme(y ~ T+t*T, random = ~1|as.factor(ID),correlation = corAR1(),data = m2)
summary(fm3)
```
```{r}
m2$resid <- resid(fm3)
acf(m2[m2$ID==11,]$resid)
```
```{r}
m2$y <- as.factor(m2$y)
ordnal2 <- clmm(ordered(y) ~ T+t*T + (1 | as.factor(ID)), data = m2)
summary(ordnal2)
```
##Jump to Negative Conclusions
```{r}
newdata <- data[which(data$...3=="Jump to Negative Conclusions"),]
newdata <- newdata[,-c(1:3)]
p <- as.matrix(newdata)
y <- c(t(p))
y <- y[!is.na(y)] 
t <- c(1:22,1:29,1:22,1:36,1:29,1:29,1:35,1:29)
T <- c(rep(0,14),rep(1,8),rep(0,21),rep(1,8),rep(0,14),rep(1,8),rep(0,28),rep(1,8),rep(0,21),rep(1,8),rep(0,21),rep(1,8),rep(0,28),rep(1,7),rep(0,21),rep(1,8))
ID <- c(rep(1,22),rep(5,29),rep(3,22),rep(6,36),rep(9,29),rep(12,29),rep(11,35),rep(17,29))
m3 <- data.frame(y,ID,t,T)
m3$y <- as.numeric(y)
```
```{r}
model5 <- lmer(y ~ T + t*T + (1 | as.factor(ID)), data = m3)
m3$y_pred <- fitted(model5)
summary(model5)
```
```{r}
ggplot(m3, mapping = aes(x=t, y=y_pred, group=as.factor(ID))) +
  geom_line()+geom_line(aes(x=t, y=y, group=as.factor(ID), colour=as.factor(ID))) +facet_wrap(~ID)+ggtitle("Jump to Negative Conclusions")+geom_vline(data = vline_data, aes(xintercept = xintercept, group = as.factor(ID)), linetype = "dashed")
```

```{r}
m3$resid <- resid(model5)
acf(m3[m3$ID==11,]$resid)
```
```{r}
fm4 <- lme(y ~ T+t*T, random = ~1|as.factor(ID),correlation = corAR1(),data = m3)
summary(fm4)
```
```{r}
m3$resid <- resid(fm4)
acf(m3[m3$ID==11,]$resid)
```
```{r}
m3$y <- as.factor(m3$y)
ordnal3 <- clmm(ordered(y) ~ T+t*T + (1 | as.factor(ID)), data = m3)
summary(ordnal3)
```

##Scares Me when I am Nervous
```{r}
newdata <- data[which(data$...3=="Scares Me when I am Nervous"),]
newdata <- newdata[,-c(1:3)]
p <- as.matrix(newdata)
y <- c(t(p))
y <- y[!is.na(y)] 
t <- c(1:22,1:29,1:22,1:36,1:29,1:29,1:35,1:29)
T <- c(rep(0,14),rep(1,8),rep(0,21),rep(1,8),rep(0,14),rep(1,8),rep(0,28),rep(1,8),rep(0,21),rep(1,8),rep(0,21),rep(1,8),rep(0,28),rep(1,7),rep(0,21),rep(1,8))
ID <- c(rep(1,22),rep(5,29),rep(3,22),rep(6,36),rep(9,29),rep(12,29),rep(11,35),rep(17,29))
m4 <- data.frame(y,ID,t,T)
m4$y <- as.numeric(y)
```




```{r}
model6 <- lmer(y ~ T+ t*T + (1 | as.factor(ID)), data = m4)
m4$y_pred <- fitted(model6)
summary(model6)
```
```{r}
ggplot(m4, mapping = aes(x=t, y=y_pred, group=as.factor(ID))) +
  geom_line()+geom_line(aes(x=t, y=y, group=as.factor(ID), colour=as.factor(ID))) +facet_wrap(~ID)+ggtitle("Scares Me when I am Nervous")+geom_vline(data = vline_data, aes(xintercept = xintercept, group = as.factor(ID)), linetype = "dashed")
```
```{r}
m4$resid <- resid(model6)
acf(m4[m4$ID==1,]$resid)
```
```{r}
fm5 <- lme(y ~ T+t*T, random = ~1|as.factor(ID),correlation = corAR1(),data = m4)
summary(fm5)
```
```{r}
m4$resid <- resid(fm5)
acf(m4[m4$ID==1,]$resid)
```
```{r}
m4$y <- as.factor(m4$y)
ordnal4 <- clmm(ordered(y) ~ T+t*T + (1 | as.factor(ID)), data = m4)
summary(ordnal4)
```

##Confident in My Ability to Handle Situations
```{r}
newdata <- data[which(data$...3=="Confident in My Ability to Handle Situations"),]
newdata <- newdata[,-c(1:3)]
p <- as.matrix(newdata)
y <- c(t(p))
y <- y[!is.na(y)] 
t <- c(1:22,1:29,1:22,1:36,1:29,1:29,1:35,1:29)
T <- c(rep(0,14),rep(1,8),rep(0,21),rep(1,8),rep(0,14),rep(1,8),rep(0,28),rep(1,8),rep(0,21),rep(1,8),rep(0,21),rep(1,8),rep(0,28),rep(1,7),rep(0,21),rep(1,8))
ID <- c(rep(1,22),rep(5,29),rep(3,22),rep(6,36),rep(9,29),rep(12,29),rep(11,35),rep(17,29))
m5 <- data.frame(y,ID,t,T)
m5$y <- as.numeric(y)
```

```{r}
model7 <- lmer(y ~ T+ t*T + (1 | as.factor(ID)), data = m5)
m5$y_pred <- fitted(model7)
summary(model7)
```
```{r}
ggplot(m5, mapping = aes(x=t, y=y_pred, group=as.factor(ID))) +
  geom_line()+geom_line(aes(x=t, y=y, group=as.factor(ID), colour=as.factor(ID))) +facet_wrap(~ID)+ggtitle("Confident in My Ability to Handle Situations")+geom_vline(data = vline_data, aes(xintercept = xintercept, group = as.factor(ID)), linetype = "dashed")
```
```{r}
m5$resid <- resid(model7)
acf(m5[m5$ID==9,]$resid)
```
```{r}
fm6 <- lme(y ~ T+t*T, random = ~1|as.factor(ID),correlation = corAR1(),data = m5)
summary(fm6)
```
```{r}
m5$resid <- resid(fm6)
acf(m5[m5$ID==9,]$resid)
```
```{r}
m5$y <- as.factor(m5$y)
ordnal5 <- clmm(ordered(y) ~ T+t*T + (1 | as.factor(ID)), data = m5)
summary(ordnal5)
```

##Push Away Thoughts and Feelings I Do Not Like
```{r}
newdata <- data[which(data$...3=="Push Away Thoughts and Feelings I Do Not Like"),]
newdata <- newdata[,-c(1:3)]
p <- as.matrix(newdata)
y <- c(t(p))
y <- y[!is.na(y)] 
t <- c(1:22,1:29,1:22,1:36,1:29,1:29,1:35,1:29)
T <- c(rep(0,14),rep(1,8),rep(0,21),rep(1,8),rep(0,14),rep(1,8),rep(0,28),rep(1,8),rep(0,21),rep(1,8),rep(0,21),rep(1,8),rep(0,28),rep(1,7),rep(0,21),rep(1,8))
ID <- c(rep(1,22),rep(5,29),rep(3,22),rep(6,36),rep(9,29),rep(12,29),rep(11,35),rep(17,29))
m6 <- data.frame(y,ID,t,T)
m6$y <- as.numeric(y)
```
```{r}
model8 <- lmer(y ~ T+ t*T + (1 | as.factor(ID)), data = m6)
m6$y_pred <- fitted(model8)
summary(model8)
```
```{r}
ggplot(m6, mapping = aes(x=t, y=y_pred, group=as.factor(ID))) +
  geom_line()+geom_line(aes(x=t, y=y, group=as.factor(ID), colour=as.factor(ID))) +facet_wrap(~ID)+ggtitle("Push Away Thoughts and Feelings I Do Not Like")+geom_vline(data = vline_data, aes(xintercept = xintercept, group = as.factor(ID)), linetype = "dashed")
```
```{r}
m6$resid <- resid(model8)
acf(m6[m6$ID==9,]$resid)
```
```{r}
fm7 <- lme(y ~ T+t*T, random = ~1|as.factor(ID),correlation = corAR1(),data = m6)
summary(fm7)
```
```{r}
m6$resid <- resid(fm7)
acf(m6[m6$ID==9,]$resid)
```

```{r}
m6$y <- factor(m6$y, ordered = TRUE)
ordnal6 <- clmm(y ~ T+ t*T + (1 | as.factor(ID)), data = m6)
summary(ordnal6)
```
##Physical Feelings in My Body Scare Me
```{r}
newdata <- data[which(data$...3=="Physical Feelings in My Body Scare Me"),]
newdata <- newdata[,-c(1:3)]
p <- as.matrix(newdata)
y <- c(t(p))
y <- y[!is.na(y)] 
t <- c(1:22,1:29,1:22,1:36,1:29,1:29,1:35,1:29)
T <- c(rep(0,14),rep(1,8),rep(0,21),rep(1,8),rep(0,14),rep(1,8),rep(0,28),rep(1,8),rep(0,21),rep(1,8),rep(0,21),rep(1,8),rep(0,28),rep(1,7),rep(0,21),rep(1,8))
ID <- c(rep(1,22),rep(5,29),rep(3,22),rep(6,36),rep(9,29),rep(12,29),rep(11,35),rep(17,29))
m7 <- data.frame(y,ID,t,T)
m7$y <- as.numeric(y)
```

```{r}
model9 <- lmer(y ~ T+ t*T + (1 | as.factor(ID)), data = m7)
m7$y_pred <- fitted(model9)
summary(model9)
```
```{r}
ggplot(m7, mapping = aes(x=t, y=y_pred, group=as.factor(ID))) +
  geom_line()+geom_line(aes(x=t, y=y, group=as.factor(ID), colour=as.factor(ID))) +facet_wrap(~ID)+ggtitle("Push Away Thoughts and Feelings I Do Not Like")+geom_vline(data = vline_data, aes(xintercept = xintercept, group = as.factor(ID)), linetype = "dashed")
```
```{r}
m7$resid <- resid(model9)
acf(m7[m7$ID==1,]$resid)
```
```{r}
fm8 <- lme(y ~ T+t*T, random = ~1|as.factor(ID),correlation = corAR1(),data = m7)
summary(fm8)
```

```{r}
m7$resid <- resid(fm8)
acf(m7[m7$ID==1,]$resid)
```
```{r}
m7$y <- factor(m7$y, ordered = TRUE)
ordnal7 <- clmm(y ~ T+ t*T + (1 | as.factor(ID)), data = m7)
summary(ordnal7)
```




